name: Meow
on: [workflow_dispatch]
jobs:
  purr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build win-x64
      run: dotnet build --no-restore -c Release -r win-x64
    - name: Upload win-x64
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: win-x64
        path: SnzDiscordBot/bin/Release/net8.0/win-x64/
